import { CursorStateKey, CursorTarget } from './useCursorify.type'

export const cursorTargets = [
  'cursorify-auto',
  'cursorify-default',
  'cursorify-none',
  'cursorify-contextMenu',
  'cursorify-help',
  'cursorify-pointer',
  'cursorify-progress',
  'cursorify-wait',
  'cursorify-cell',
  'cursorify-crosshair',
  'cursorify-text',
  'cursorify-verticalText',
  'cursorify-alias',
  'cursorify-copy',
  'cursorify-move',
  'cursorify-noDrop',
  'cursorify-notAllowed',
  'cursorify-grab',
  'cursorify-grabbing',
  'cursorify-allScroll',
  'cursorify-colResize',
  'cursorify-rowResize',
  'cursorify-nResize',
  'cursorify-eResize',
  'cursorify-sResize',
  'cursorify-wResize',
  'cursorify-neResize',
  'cursorify-nwResize',
  'cursorify-seResize',
  'cursorify-swResize',
  'cursorify-ewResize',
  'cursorify-nsResize',
  'cursorify-neswResize',
  'cursorify-nwseResize',
  'cursorify-zoomIn',
  'cursorify-zoomOut',
]

export const cursorSelectors = cursorTargets
  .map((cursorTarget) => `.${cursorTarget}`)
  .join(', ')

export const initialCursorState = {
  isAuto: false,
  isDefault: false,
  isNone: false,
  isContextMenu: false,
  isHelp: false,
  isPointer: false,
  isProgress: false,
  isWait: false,
  isCell: false,
  isCrosshair: false,
  isText: false,
  isVerticalText: false,
  isAlias: false,
  isCopy: false,
  isMove: false,
  isNoDrop: false,
  isNotAllowed: false,
  isGrab: false,
  isGrabbing: false,
  isAllScroll: false,
  isColResize: false,
  isRowResize: false,
  isNResize: false,
  isEResize: false,
  isSResize: false,
  isWResize: false,
  isNeResize: false,
  isNwResize: false,
  isSeResize: false,
  isSwResize: false,
  isEwResize: false,
  isNsResize: false,
  isNeswResize: false,
  isNwseResize: false,
  isZoomIn: false,
  isZoomOut: false,
}

export const targetStateMap: {
  [cursorTarget in CursorTarget]: CursorStateKey
} = {
  'cursorify-auto': 'isAuto',
  'cursorify-default': 'isDefault',
  'cursorify-none': 'isNone',
  'cursorify-contextMenu': 'isContextMenu',
  'cursorify-help': 'isHelp',
  'cursorify-pointer': 'isPointer',
  'cursorify-progress': 'isProgress',
  'cursorify-wait': 'isWait',
  'cursorify-cell': 'isCell',
  'cursorify-crosshair': 'isCrosshair',
  'cursorify-text': 'isText',
  'cursorify-verticalText': 'isVerticalText',
  'cursorify-alias': 'isAlias',
  'cursorify-copy': 'isCopy',
  'cursorify-move': 'isMove',
  'cursorify-noDrop': 'isNoDrop',
  'cursorify-notAllowed': 'isNotAllowed',
  'cursorify-grab': 'isGrab',
  'cursorify-grabbing': 'isGrabbing',
  'cursorify-allScroll': 'isAllScroll',
  'cursorify-colResize': 'isColResize',
  'cursorify-rowResize': 'isRowResize',
  'cursorify-nResize': 'isNResize',
  'cursorify-eResize': 'isEResize',
  'cursorify-sResize': 'isSResize',
  'cursorify-wResize': 'isWResize',
  'cursorify-neResize': 'isNeResize',
  'cursorify-nwResize': 'isNwResize',
  'cursorify-seResize': 'isSeResize',
  'cursorify-swResize': 'isSwResize',
  'cursorify-ewResize': 'isEwResize',
  'cursorify-nsResize': 'isNsResize',
  'cursorify-neswResize': 'isNeswResize',
  'cursorify-nwseResize': 'isNwseResize',
  'cursorify-zoomIn': 'isZoomIn',
  'cursorify-zoomOut': 'isZoomOut',
}
